const data = [
  {
    id: 1,
    name: 'Pepper - White, Whole',
    description: 'Remove cervical cerclage',
    price: 23,
    imgURL: 'http://dummyimage.com/232x100.png/cc0000/ffffff',
    discount: 70,
  },
  {
    id: 2,
    name: 'Veal Inside - Provimi',
    description: 'Cystocel/rectocel repair',
    price: 43,
    imgURL: 'http://dummyimage.com/149x100.png/dddddd/000000',
    discount: 17,
  },
  {
    id: 3,
    name: 'Pasta - Shells, Medium, Dry',
    description: 'Thorac esophag anast NEC',
    price: 68,
    imgURL: 'http://dummyimage.com/107x100.png/5fa2dd/ffffff',
    discount: 54,
  },
  {
    id: 4,
    name: 'Bread - Italian Roll With Herbs',
    description: 'Middle ear incision',
    price: 79,
    imgURL: 'http://dummyimage.com/205x100.png/cc0000/ffffff',
    discount: 45,
  },
  {
    id: 5,
    name: 'Raspberries - Fresh',
    description: 'Type 5 tympanoplasty',
    price: 31,
    imgURL: 'http://dummyimage.com/147x100.png/ff4444/ffffff',
    discount: 11,
  },
  {
    id: 6,
    name: 'Wine - Riesling Dr. Pauly',
    description: 'Mech remov cornea epith',
    price: 65,
    imgURL: 'http://dummyimage.com/228x100.png/cc0000/ffffff',
    discount: 4,
  },
  {
    id: 7,
    name: 'Dc - Sakura Fu',
    description: 'Close red-humerus epiphy',
    price: 6,
    imgURL: 'http://dummyimage.com/179x100.png/cc0000/ffffff',
    discount: 88,
  },
  {
    id: 8,
    name: 'Wine - Merlot Vina Carmen',
    description: 'Heart transplantation',
    price: 51,
    imgURL: 'http://dummyimage.com/102x100.png/cc0000/ffffff',
    discount: 96,
  },
  {
    id: 9,
    name: 'Salmon Steak - Cohoe 6 Oz',
    description: 'Heart vessel op NEC',
    price: 96,
    imgURL: 'http://dummyimage.com/125x100.png/5fa2dd/ffffff',
    discount: 73,
  },
  {
    id: 10,
    name: 'Phyllo Dough',
    description: 'Barium swallow',
    price: 40,
    imgURL: 'http://dummyimage.com/187x100.png/5fa2dd/ffffff',
    discount: 69,
  },
  {
    id: 11,
    name: 'Sun - Dried Tomatoes',
    description: 'Dorsal/lat slit prepuce',
    price: 56,
    imgURL: 'http://dummyimage.com/227x100.png/cc0000/ffffff',
    discount: 80,
  },
  {
    id: 12,
    name: 'Scallops 60/80 Iqf',
    description: 'Limb shorten-radius/ulna',
    price: 79,
    imgURL: 'http://dummyimage.com/177x100.png/dddddd/000000',
    discount: 1,
  },
  {
    id: 13,
    name: 'Beer - Tetleys',
    description: 'Full-thick hand skin grf',
    price: 78,
    imgURL: 'http://dummyimage.com/173x100.png/dddddd/000000',
    discount: 2,
  },
  {
    id: 14,
    name: 'Pasta - Fusili Tri - Coloured',
    description: 'Orbital exenteration NEC',
    price: 46,
    imgURL: 'http://dummyimage.com/226x100.png/5fa2dd/ffffff',
    discount: 37,
  },
  {
    id: 15,
    name: 'Soup - Campbells Chili Veg',
    description: 'Adjust lid position NEC',
    price: 83,
    imgURL: 'http://dummyimage.com/175x100.png/5fa2dd/ffffff',
    discount: 33,
  },
  {
    id: 16,
    name: 'Strawberries',
    description: 'Tendon graft',
    price: 86,
    imgURL: 'http://dummyimage.com/173x100.png/5fa2dd/ffffff',
    discount: 51,
  },
  {
    id: 17,
    name: 'Nut - Peanut, Roasted',
    description: 'Otoscopy',
    price: 41,
    imgURL: 'http://dummyimage.com/208x100.png/dddddd/000000',
    discount: 50,
  },
  {
    id: 18,
    name: 'Gatorade - Cool Blue Raspberry',
    description: 'Female genital x-ray NEC',
    price: 64,
    imgURL: 'http://dummyimage.com/233x100.png/dddddd/000000',
    discount: 96,
  },
  {
    id: 19,
    name: 'Wine - Sherry Dry Sack, William',
    description: 'Distal gastrectomy',
    price: 47,
    imgURL: 'http://dummyimage.com/166x100.png/dddddd/000000',
    discount: 10,
  },
  {
    id: 20,
    name: 'Wine - Red, Cooking',
    description: 'Nephrotomogram NEC',
    price: 40,
    imgURL: 'http://dummyimage.com/185x100.png/5fa2dd/ffffff',
    discount: 74,
  },
];

export default data;
